# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        #in_memory:
            #memory: ~

        foggyline_customer:
            entity:
                class: FoggylineCustomerBundle:Customer
                property: username

    encoders:
        #Symfony\Component\Security\Core\User\User:
            #algorithm: bcrypt
            #cost: 12

        Foggyline\CustomerBundle\Entity\Customer:
            algorithm: bcrypt
            cost: 12

    firewalls:

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        #main:
            #anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

        foggyline_customer:
            #pattern:   ^/(?!user)
            anonymous: ~
            provider: foggyline_customer
            form_login:
                login_path: foggyline_customer_login #/customer/login
                check_path: foggyline_customer_login
                default_target_path: customer_account
            logout:
                path:   /customer/logout
                target: /

    access_control:
        #- { path: customer/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: customer/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: customer/forgotten_password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: /customer/account, roles: [ROLE_ADMIN,ROLE_USER] }
        #- { path: customer/logout, roles: ROLE_USER }
        - { path: /customer/index, roles: ROLE_ADMIN }
        - { path: /new, roles: ROLE_ADMIN }
        - { path: /edit, roles: ROLE_ADMIN }
        - { path: /, roles: ROLE_ADMIN, methods: [DELETE] }